'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert(
      'places',
      [
        {
          name: "UABCS",
          lat: "24.101493",
          long: "-110.314203",
          dir: "Universidad Autónoma de Baja California Sur, Carretera al Sur KM 5.5 Col Mezquitito. La Paz, B.C.S.",
          color: "red darken-4",
          img: "https://www.mexicoescultura.com/galerias/espacios/principal/image65.jpg",
          rank: 3.5,
          price: "$$",
          cat: "Universidad, Casa de Estudios",
          desc: "La Universidad Autónoma de Baja California Sur es una Institución pública que ofrece programas educativos de calidad; genera y divulga conocimiento científico, tecnológico y humanístico de vanguardia;",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          name: "Terminal del Malecón",
          lat: "24.163839",
          long: "-110.315757",
          dir: "Av. Álvaro Obregón entre 5 de Mayo e Independencia. La Paz, B.C.S.",
          color: "#093479",
          img: "https://2.bp.blogspot.com/-Qbd6fDRk4AM/WmAyPmysw3I/AAAAAAAAkWI/r-tbXAUmLI8Tdr6r-JyYx6N9W1yVh6KdQCLcBGAs/s1600/50-5.%2BLa%2BPaz%2B%252817%2529.JPG",
          rank: 5.0,
          price: "$$$",
          cat: "Terminal, Autobuses, Aguila, Abc",
          desc: "Av Alvaro Obregón, sobre el Malecón, entre la Avenida 5 de Mayo y la Calle, Independencia, Universidad Autónoma de Baja California Sur, La Paz, B.C.S.",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Terminal Águila 8 de Oct.",
          lat: "24.115778",
          long: "-110.311509",
          dir: "Blvd. Forjadores y Lic. Angel Aramburo, CP: 23086, La Paz, B.C.S.",
          color: "#4f91cc",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS4XSmef4y7TUrYeX8iP66EBhkqL0slDvlIi05KuGVAyn4T57aS",
          rank: 3.5,
          price: "$$$",
          cat: "Terminal, Autobuses, Aguila",
          desc: "Lic Ángel César Mendoza Arámburo, 23086 La Paz, B.C.S.",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Colonia Colina del Sol",
          lat: "24.170973",
          long: "-110.300435",
          dir: "Fraccionamiento Colina del Sol CP: 23010, La Paz, B.C.S.",
          color: "teal",
          img: "https://propiedadescom.s3.amazonaws.com/files/292x200/colina-del-sol-la-paz-baja-california-sur-11265563-foto-01.jpg",
          rank: 5.0,
          price: "$$$$",
          cat: "Residencial, Fraccionamiento",
          desc: "Conoce las casas en Colina del Sol, La Paz, Baja California Sur, desde $ 2.71 MDP hasta $ 6 MDP. Encuentra la mayor oferta de casas en Colina del Sol",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Colonia Camino Real",
          lat: "24.055845",
          long: "-110.297903",
          dir: "Colonia El Camino Real esquina con fin del mundo a orillas de La Paz, B.C.S.",
          color: "red darken-4",
          img: "https://www.elsudcaliforniano.com.mx/incoming/1lgfg6-ventajas-y-desventajas-de-vivir-en-camino-real/alternates/LANDSCAPE_400/Ventajas%20y%20desventajas%20de%20vivir%20en%20Camino%20Real",
          rank: 4.0,
          price: "$$",
          cat: "Camino Real, Colonia",
          desc: "Camino Real, es un fraccionamiento, más conocido como Colonia, que se encuentra ubicado en una de las zonas más alejadas al centro de la ciudad de La Paz, en el estado de Baja California Sur",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Soriana Forjadores",
          lat: "24.125310",
          long: "-110.312535",
          dir: "Blvd. Forjadores esq. Colosio, La Paz, B.C.S.",
          color: "orange darken-3",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcStDkHwbi8p4_W3MDXDQMTM16wNiYngTeGgD26m_Gl-DstljH4z",
          rank: 4.5,
          price: "$$",
          cat: "Soriana, Abarrotes, Vinos y Licores",
          desc: "La Paz Bc. Blvd. Forjadores de SudCalifornia esq. Av. Luis Donaldo Colosio; S/N; La Paz; 23000; Mexico; 6121214771.",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Soriana Mi Plaza",
          lat: "24.140040",
          long: "-110.333833",
          dir: "Calle Abasolo junto a Cinemex Mi Plaza, La Paz, B.C.S.",
          color: "orange darken-4",
          img: "https://imganuncios.mitula.net/locales_disponibles_en_mi_plaza_la_paz_antes_mega_desde_30m2_2780056544278218046.jpg",
          rank: 5.0,
          price: "$$",
          cat: "Soriana, Abarrotes, Vinos y Licores",
          desc: "Contamos con anclas Soriana y Cinemex, subanclas Modatelas, Dax, Family Fitness y Offi ... 16 de septiembre entre revolucion, Centro SCT Baja California Sur.",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Sushi Factory",
          lat: "24.126040",
          long: "-110.312753",
          dir: "Blvd. Forjadores dentro de Plaza La Paz, frente a Cinepolis. La Paz, B.C.S.",
          color: "green darken-1",
          img: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQm4jd9UuUZpbT8JqLX4fgKXGewoXZdZc0B_3O2vS1XO4P-pLAc",
          rank: 4.2,
          price: "$$$$",
          cat: "Sushi, Teriyaki, Comida Oriental",
          desc: "Cocina china, sushi y teppanyaki ofrecido en un moderno local familiar dentro de una plaza comercial.",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Sushi Tabu",
          lat: "24.137854",
          long: "-110.312327",
          dir: "Blvd. Forjadores pasando Electra. La Paz, B.C.S.",
          color: "red accent-4",
          img: "https://www.elsudcaliforniano.com.mx/incoming/skr8vj-tabu-3/ALTERNATES/LANDSCAPE_1140/Tab%C3%BA%20(3)",
          rank: 4.5,
          price: "$$$",
          cat: "Sushi, Tragos, Margaritas",
          desc: "Veracruz S/N, Las Garzas, 23079 La Paz, B.C.S.",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        }, {
          name: "Sushi Longer",
          lat: "24.153675",
          long: "-110.324183",
          dir: "Abasolo y Marquez de Leon, en el estacionamiento de Arjona. La Paz, B.C.S.",
          color: "blue-grey darken-1",
          img: "https://lh3.googleusercontent.com/p/AF1QipOmMOJtdBzW-VaDVZW9BLGsTX3Mqv1B0l7lSOtd=w600-k",
          rank: 5.0,
          price: "$$",
          cat: "Sushi, Malecon, Carrito",
          desc: "El mejor pinshi sushi de toda La Paz, BCS es aqui mero",
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
    ], {});
  },

  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('places', null, {})

};
